# Generated by Django 6.0.6 on 2026-06-04 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_usuario_responsavel'),
        ('usuarios', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
